from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from crime import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crime.urls')),
    path('index/', include('crime.urls')),
    path('regcode/', include('crime.urls')),
    path('login/', include('crime.urls')),
    path('logincode/', include('crime.urls')),
    path('user/', include('crime.urls')),
    path('admin1/', include('crime.urls')),
    path('logout/', include('crime.urls')),
    path('addnews/', include('crime.urls')),
    path('missing/', include('crime.urls')),
    path('wanted/', include('crime.urls')),
    path('fir/', include('crime.urls')),
    path('register/', include('crime.urls')),
    path('history/', include('crime.urls')),
    path('d_news/', include('crime.urls')),
    path('d_missing/', include('crime.urls')),
    path('d_wanted/', include('crime.urls')),
    path('d_fir/', include('crime.urls')),
    path('d_register/', include('crime.urls')),
    path('d_history/', include('crime.urls')),
    path('delete_wanted/', include('crime.urls')),
    path('delete_news/', include('crime.urls')),
    path('delete_missing/', include('crime.urls')),
    path('delete_fir/', include('crime.urls')),
    path('delete_register/', include('crime.urls')),
    path('delete_history/', include('crime.urls')),
    path('editprofile/', include('crime.urls')),
    path('u_complaint/', include('crime.urls')),
    path('s_complaint/', include('crime.urls')),
    path('delete_cmp/', include('crime.urls')),
    path('u_crime/', include('crime.urls')),
    path('s_crime/', include('crime.urls')),
    path('delete_crime/', include('crime.urls')),
    path('u_message/', include('crime.urls')),
    path('s_message/', include('crime.urls')),
    path('delete_message/', include('crime.urls')),
    path('s_news/', include('crime.urls')),
    path('s_missing/', include('crime.urls')),
    path('s_wanted/', include('crime.urls')),
    path('s_fir/', include('crime.urls')),
    path('s_register/', include('crime.urls')),
    path('s_history/', include('crime.urls')),
    path('user_complaint/', include('crime.urls')),
    path('user_crime/', include('crime.urls')),
    path('user_message/', include('crime.urls')),
    path('cmp_rpy/', include('crime.urls')),
    path('crime_rpy/', include('crime.urls')),
    path('msg_rpy/', include('crime.urls')),
    path('cmp_reply/', include('crime.urls')),
    path('crime_reply/', include('crime.urls')),
    path('msg_reply/', include('crime.urls')),
]
