# Generated by Django 2.1.5 on 2019-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pictures/')),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
