# Generated by Django 2.1.5 on 2019-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0004_addwanted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addfir',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('iproof', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='fir/')),
                ('case1', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
