# Generated by Django 2.1.5 on 2019-04-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0007_addhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcmp',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('case1', models.TextField(max_length=500)),
            ],
        ),
    ]
